[theme]

# Primary accent for interactive elements
primaryColor = '#b3a369'

# Background color for the main content area
backgroundColor = '#154734'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#237757'

# Color used for almost all text
textColor = '#f4f5f0'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"


[runner]

magicEnabled = false